language: R
warnings_are_errors: true
notifications:
  email:
    recipients:
      # - michael.mastanduno@healthcatalyst.com
      # - levi.thatcher@healthcatalyst.com
      # - taylor.larsen@healthcatalyst.com
      # - taylor.miller@healthcatalyst.com
      - michael.levy@healthcatalyst.com
    on_success: never
    on_failure: always
  slack:
    secure: KIZYbmeATHXsbryDcrq6b4H6gtg3vrZIqZArbBpXd9Xp5ApHuGs0PYrYfWWMJmrZH+kNI4OK9DxxFRZdu59955Khev3dNyuGTMS0yRaRvqypi+0LUzbw+ha938l5Y3/OnK0Ke6WvX97r0xDX1vr5c/NMVzecZQGgIzi3PVY9TE1woXabtDlD7yvs2CrGabifGQUfkvEdRgGFUCXqPgckC4I66wVHJp6EWvVqiSPnsmMHEtTUnYmgxlR9YDPKHz/AKVKhvSh3ny4BoLBODqZuHSda4s8vtB8fNQMlXp0L+6lb1Y7tdXurfwUpde4uXfl5iCS8h/6h3Fk2WMjooztDdXCHqPLOKCXcqaJQELlYH4IBZPO/CIz2ljfp8SH4QXn5Bjm4ZJbfYGZiqmwlngJ7TZdtEyVsfL5JzjdsMucL4MOfZSKUypDERZVqdnKZmNfIfe5d410v08zNBrJ0lLezQMAwT+hNJejja88NMlRQKMRDuCxn01hUfGNRkZWyVhpdU6yry7cGSKM5np+/Rnjqf9BXevMv4h3HNpeSCzzugpCZFwOlC31Tny4j/hQOz3CHluNaHTSaf+eFV+6MX+OFIAwuuVTuxC0To5PA59JHkl+XiUssxIDMifsyBRxCm4+fxWZUsYXd0u7l81ultEJ78R41K6cwx2fOxhL3UE3obPQ=

language: r
matrix:
  include:
  - os: linux
    cache: packages
    dist: trusty
    sudo: false
    r:
    - release
    - devel
  - os: osx
    cache: packages
    osx_image: xcode8.2
    sudo: required
    r: 
    - release
    - devel
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    # packages:
    #   - clang-format-3.9

before_install:  Rscript -e 'update.packages(ask = FALSE)'

after_success:
  - Rscript -e 'covr::codecov()'
